### PR TITLE
add support for fullscreen images

### PR DESCRIPTION
**Pull request by d6p2b**
Addresses issue #14 by allowing a mixture of partial- and full-screen images for the onboarding experience.  I also added support for decorating the progress button container in case it needs to sit on top of a dark image.

### CODE REVIEW

**Comment by AgustinV08** [comment]
When will this PR be merged?

**Comment by Julianojc** [comment]
When will this PR be merged?²

**Comment by thoffart** [comment]
any news about this PR?

**Comment by SalahAdDin** [comment]
This repo seems to be dead.

**Comment by Pyozer** [comment]
Hi, sorry I haven't time to maintain this repo correctly...  I will try tomorrow to update it :/

**Comment by AgustinV08** [comment]
@Pyozer Thanks a lot, i understand if you don't have always time to maintain the repo

**Pull request merged**
