### PR TITLE
Significant rewrite, fixing broken code (in readme)

### PR DESCRIPTION
**Pull request by EnduringBeta**
I mostly stopped at Parameter Lists.

### CODE REVIEW

**Comment by ghenry** [comment]
Anyone reviewed this?

**Comment by ghenry** [comment]
Happy to help review all PRs and unanswered/outstanding issues as I'm looking to use this for one of my projects.

Thanks.

**Comment by Pyozer** [comment]
Hi @ghenry,

Would you be interested in helping me maintain the project?

Actually I don't have the time anymore to maintain it and I confess a little less motivation.
So I'm having a hard time maintaining the project, reviewing the PR and the issues.

**Comment by ghenry** [comment]
Yeah, no problem.

**Comment by Pyozer** [comment]
Nice, thank you ;)
I've invited you to have access of the project

**Comment by ghenry** [comment]
I'll do my best 😁 You'll still be around to ask questions, right?

**Comment by Pyozer** [comment]
Yes of course ;)

**Pull request merged**
