### PR TITLE
some changes and fixes to auto scroll

### PR DESCRIPTION
**Pull request by Macacoazul01**

### CODE REVIEW

**Review by ghenry — COMMENTED** [review]
Is this a breaking change removing those options?

**Comment by Macacoazul01** [comment]
Unfortunately it is kind of...

The behavior of the package will remain as the safe list replace these options, but as they will be removed, it can break some users code.

**Comment by Macacoazul01** [comment]
As there is already the dots to int breaking that wasn't added officially to a version, I took the opportunity to do this one too

**Comment by ghenry** [comment]
Didn't we revert that and want to do a breaking  change major version? Can't recall.

**Comment by Macacoazul01** [comment]
Nope
It was merged (pr #180)

**Pull request merged**
