### PR TITLE
[feature] hide back/next buttons when !canProgess

### PR DESCRIPTION
**Pull request by floffel**
Idea: Hide the buttons that have no effect.
I only added it for back/next buttons (as they progress the pages), not for the done button.

### CODE REVIEW

**Comment by Macacoazul01** [comment]
Gonna check later today. Tks for the PR.

**Comment by orkun1675** [comment]
This PR breaks the `Done` button for me. I cannot proceed to the last page and the `Done` button does not show up.

Could someone else test as well?

If we can replicate, please revert this PR.

**Comment by ghenry** [comment]
Thanks for testing!

**Comment by orkun1675** [comment]
Turns out this PR was not the culprit but it was the one after.

Offered a fix in https://github.com/Pyozer/introduction_screen/pull/210.

Thanks!

**Pull request merged**
