### PR TITLE
Null safety support

### LINKED ISSUE #57: null-safety Support
It would be nice if the plugin would also support for Dart null safety, which is being enforced by upcoming flutter releases. For details, refer to: https://dart.dev/null-safety

### LINKED ISSUE #59: null-safety support required

### PR DESCRIPTION
**Pull request by leynier**
IMPORTANT!!! This PR should not be merge yet, because the `dots_indicator` dependency does not have support for **Null safety** yet, meanwhile a PR of this dependency is being used (https://github.com/Pyozer/dots_indicator/pull/15).

This PR also updated the sample application to Flutter 2 and implemented web support for it.

Please, when the dependency is migrated to Null safety let me know to use it directly so that this PR can be merged perfectly.

Fix #57
Fix #59

### CODE REVIEW

**Comment by leynier** [comment]
@Pyozer  This PR is ready, it can be reviewed.

**Comment by Pyozer** [comment]
Thanks @leynier, I will merge it and publish new version ;)

**Comment by Pyozer** [comment]
v2.0.0 Published, thx again ;)

**Comment by leynier** [comment]
> v2.0.0 Published, thx again ;)

Thanks to you for develop this package 👏🏻👏🏻👏🏻

**Pull request merged**
